all:
  vars:
    ansible_connection: ssh
    ansible_ssh_user: haochuan
    ansible_become: true
    security_mode: plaintext
preflight:
  hosts:
    10.0.29.153:
zookeeper:
  hosts:
    10.0.29.153:
broker:
  hosts:
    10.0.29.153:
      kafka:
        broker:
          id: 1
schema-registry:
  hosts:
    ip-172-31-10-207.us-east-2.compute.internal:
control-center:
  hosts:
    ip-172-31-5-30.us-east-2.compute.internal:
      confluent:
        control:
          center:
            config:
              confluent.controlcenter.connect.cluster: ip-172-31-10-207.us-east-2.compute.internal:8083
connect-distributed:
  hosts:
    ip-172-31-10-207.us-east-2.compute.internal:
kafka-rest:
  hosts:
    ip-172-31-10-207.us-east-2.compute.internal:
ksql:
  hosts:
    ip-172-31-5-30.us-east-2.compute.internal:
